title: Tyler Wang's Class Notes
site-title: Class Notes
subtitle: >- # this means to ignore newlines until "baseurl:"
description: >- # this means to ignore newlines until "baseurl:"
  Links to all of Tyler Wang's class notes.
baseurl: "" # add /blog
url: "https://class.tylerwang.org" # the base hostname & protocol for your site, e.g. http://example.com

email: wangtyler123@gmail.com
name: "Tyler Wang"
about: >-
  University of Illinois Urbana-Champaign<br/>
  Physics BS <br/>
  Mathematics BSLAS <br/>
social:
  github: tylerwwang
  linkedin: https://www.linkedin.com/in/tyler-wang-472261213/
  website: https://tylerwang.org

# Build settings
markdown: kramdown
permalink: pretty
timezone: America/Chicago
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

google_analytics: G-EHTE346B6V

menu-pages:
  - Precalculus
